#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg TAG=${VERSION} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --tag ${REPO}/${PROG}-runtime-cilium:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-runtime-cilium:${DOCKERIZED_VERSION}-${GOARCH} \
    --file Dockerfile-cilium \
    --target runtime-cilium \
.

mkdir -p build/images
docker image save \
    --output build/images/${PROG}-runtime.tar \
    ${REPO}/${PROG}-runtime-cilium:${DOCKERIZED_VERSION} \
    ${REPO}/${PROG}-runtime-cilium:${DOCKERIZED_VERSION}-${GOARCH}
